### ISSUE TITLE
Inverting the table order

### ISSUE THREAD

**Issue by slnkahveci** [K-Trout/truthtable#2]
Hi, I was wondering if there is an option to invert the table order somehow. (from FFF to TTT)

**Comment by K-Trout** [comment]
Hey
I'm afraid there's no such option at the moment.
If I have time to create an update for the package in the future, I'll consider this as a feature to add.
Thank you for your message and your interest.

**Comment by slnkahveci** [comment]
Thank you for your feedback. I added an optional parameter to my fork that may be useful. Let me know if you have further suggestions. And thanks for sharing this package.

**Comment by K-Trout** [comment]
Hey
Thanks again for your suggestion, in the new release of the package, tables can be generated in both directions. The updated version should be available soon over CTAN as well.
