### ISSUE TITLE
First column and alignment

### ISSUE THREAD

**Issue by cpierquet** [K-Trout/truthtable#3]
Hi- Tks for the package ;-)

Just a question, as you can see in the screen, the first column of the generate table isn't correctly centered :-)

```
%!TEX lualatex

\documentclass{article}
\usepackage{truthtable}

\begin{document}

\begin{tabular}{|c|c||c|c|c|c|c|c|c}
% Content of table is generated using this single command.
\hline
\truthtable{A,B}{$A$,$B$}{!A, A & B, A | B}{$\lnot A$, $A \land B$, $A \lor B$}{$T$}{$F$}
\hline
\end{tabular}

\end{document}

```
![image](https://github.com/K-Trout/truthtable/assets/45103962/622e24c4-3bd2-4dea-a3ee-f8d0a0d6aef7)

**Comment by K-Trout** [comment]
Hey
Thanks for liking the package.
Also, thanks for bringing this to my attention. When I get to work on this again, I will look into it.

**Comment by K-Trout** [comment]
Hey again, got to it quicker than I thought.
Thanks again for your notice, the bug should be fixed in this new version. The update should drop on CTAN soon.
